Drop unnecessary "move()" from await_connection() (#1998)
I'm building rr on Linux using Clang trunk from ~last week, and I'm getting this build warning (treated as an error):
````
rr/src/GdbServer.cc:1369:10: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
  return move(dbg);
         ^
rr/rr/src/GdbServer.cc:1369:10: note: remove std::move call here
  return move(dbg);
         ^~~~~   ~
````

Source link:
https://github.com/mozilla/rr/blob/2e4fd448052aec5592871c82e1de500a3925aaeb/src/GdbServer.cc#L1364-L1369

Turns out the "move" wrapper here is unnecessary (and somewhat problematic for optimizations, as noted in the warning).  Easy fix: just drop the "move".  It's fine to return unique_ptr by value -- see the sample function "pass_through" on http://en.cppreference.com/w/cpp/memory/unique_ptr