[kernel-abi] Don't use a reserved keyword.
__unused is reserved by compilers somehow (even though it's an
extension) so compiling this code with clang on FreeBSD results
in an error, i.e.

/home/davide/rr/src/kernel_abi.h:1046:27: error: expected member
name or ';' after declaration specifiers
    unsigned_long __unused[4];
    ~~~~~~~~~~~~~         ^

Rename to avoid the clash.