Mark parameter fd to ElfFileReader::is_x32_abi as possibly unused.
When building for 32-bit:
ElfReader.cc:516:42: error: unused parameter ‘fd’

Related commit: 998f91090d