Fix build in newer glibc.
Seems tgkill was added recently to glibc.

build/32/tgkill.c:7:12: error: static declaration of 'tgkill' follows non-static declaration
static int tgkill(int tgid, int tid, int sig) {
           ^
/usr/include/bits/signal_ext.h:29:12: note: previous declaration is here
extern int tgkill (__pid_t __tgid, __pid_t __tid, int __signal);