Add mode flag argument to open calls in tests that may create files
When an open call may create a file it should include an argument for
the file's mode flags.  In some configurations the missing mode flag
argument will cause the the build to fail like the following:

/usr/include/bits/fcntl2.h:50:4: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
   50 |    __open_missing_mode ();
      |    ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/mmap_shared_write.dir/build.make:66: CMakeFiles/mmap_shared_write.dir/src/test/mmap_shared_write.c.o] Error 1