Add PTRACE_GETFPXREGS and PTRACE_SETFPXREGS to own declarations.
Since ead024c06 the force32bit build fails with:
error: ‘PTRACE_GETFPXREGS’ was not declared in this scope