Fix 32-bit build by adding cast.
Related to commit 5c6e992b2ad1.
----
error: invalid cast from type ‘uintptr_t’ {aka ‘unsigned int’} to type ‘uint64_t’ {aka ‘long long unsigned int’}