Have own definition for SEGV_PKUERR if system is missing it.
ReplaySession.cc:1113:63: error: ‘SEGV_PKUERR’ was not declared in this scope

Related to build issue at Ubuntu 16.04 LTS: #2919