Use the explicit variant, because statx is also known as function name.
Got this error:
src/kernel_abi.cc:68:55: error: type/value mismatch at argument 2 in template parameter list for ‘template<rr::SupportedArch a, class system_type, class rr_type> struct rr::Verifier’
src/kernel_abi.cc:68:55: note:   expected a type, got ‘statx’